export interface TemplateMetadata {
  id: string;
  slug: string;
  name: string;
  description: string;
  previewUrl: string;
  tags: string[];
  category: string;
  isPremium: boolean;
  themeColors: string[];
  features: string[];
  sortOrder: number;
}

export const TEMPLATES: TemplateMetadata[] = [
  {
    id: "tmpl-clean-starter",
    slug: "clean-starter",
    name: "Clean Starter",
    description: "Clean, professional portfolio with a minimal modern design. Free to generate — no credits needed!",
    previewUrl: "/templates/previews/clean-starter.png",
    tags: ["Minimalist", "Clean", "Light", "Single Column"],
    category: "minimal",
    isPremium: false,
    themeColors: ["#7C3AED", "#10B981", "#EF4444", "#3B82F6"],
    features: ["Clean Design", "Responsive", "Smooth Animations"],
    sortOrder: 1,
  },
  {
    id: "tmpl-modern-developer",
    slug: "modern-developer",
    name: "Modern Developer",
    description: "Dark sidebar and code-editor-inspired content area. Ideal for Software Engineers and Tech Lead portfolios.",
    previewUrl: "/templates/previews/modern-developer.png",
    tags: ["Dark Mode", "Developer", "Sidebar", "Tech-themed"],
    category: "tech",
    isPremium: false,
    themeColors: ["#06B6D4", "#7C3AED", "#10B981", "#F59E0B"],
    features: ["Code Syntax Highlighting Style", "Left-Hand Sticky Navigation", "Detailed Tech Stack Tags"],
    sortOrder: 2,
  },
  {
    id: "tmpl-apple-style",
    slug: "apple-style",
    name: "Apple Style",
    description: "Full-bleed sections, SF Pro typography, and slick high-end aesthetic inspired by Apple's product design.",
    previewUrl: "/templates/previews/apple-style.png",
    tags: ["Minimalist", "Sleek", "Bold Text", "Full-bleed"],
    category: "design",
    isPremium: true,
    themeColors: ["#111111", "#7C3AED", "#6B7280", "#3B82F6"],
    features: ["Interactive Scroll Reveal", "Premium Product Cards", "Ultra-Clean Headers"],
    sortOrder: 3,
  },
  {
    id: "tmpl-linear-style",
    slug: "linear-style",
    name: "Linear Style",
    description: "Ultra-minimal dark mode layout using JetBrains Mono. Modeled after Linear's developer tool layout.",
    previewUrl: "/templates/previews/linear-style.png",
    tags: ["Dark Mode", "Monospace", "Productivity", "Subtle Border"],
    category: "tech",
    isPremium: true,
    themeColors: ["#5E6AD2", "#06B6D4", "#F59E0B", "#10B981"],
    features: ["Grid Layout Lines", "Subtle Keyboard Action Badges", "Custom Task List Styles"],
    sortOrder: 4,
  },
  {
    id: "tmpl-saas-dashboard",
    slug: "saas-dashboard",
    name: "SaaS Dashboard",
    description: "Card-based dashboard layout presenting sections like modules. Data-forward style.",
    previewUrl: "/templates/previews/saas-dashboard.png",
    tags: ["Dashboard", "Grid Layout", "Analytics Look", "Tailwind Theme"],
    category: "business",
    isPremium: false,
    themeColors: ["#2563EB", "#7C3AED", "#059669", "#D97706"],
    features: ["Visual Status Flags", "Collapsible Project Summary Blocks", "Metrics Summary Board"],
    sortOrder: 5,
  },
  {
    id: "tmpl-glass-universe",
    slug: "glass-universe",
    name: "Glass Universe",
    description: "Glassmorphism styling, frosted glass cards, and blurred interactive gradient orbs floating in back.",
    previewUrl: "/templates/previews/glass-universe.png",
    tags: ["Glassmorphism", "Fluid Gradients", "Vibrant", "Modern UI"],
    category: "creative",
    isPremium: true,
    themeColors: ["#EC4899", "#8B5CF6", "#3B82F6", "#10B981"],
    features: ["Frosted Backdrop Blur Layers", "Dynamic Floating Background Shapes", "Glow Borders"],
    sortOrder: 6,
  },
  {
    id: "tmpl-cyberpunk",
    slug: "cyberpunk",
    name: "Cyberpunk 2077",
    description: "High-contrast neon green/cyan/magenta grid lines, digital terminals, glow accents and raw industrial style.",
    previewUrl: "/templates/previews/cyberpunk.png",
    tags: ["Cyberpunk", "Terminal", "Neon", "Glow Effects"],
    category: "creative",
    isPremium: true,
    themeColors: ["#FACC15", "#06B6D4", "#EC4899", "#10B981"],
    features: ["Neon Text Glow Animation", "Terminal Command Simulation Headers", "Glitch Hover Triggers"],
    sortOrder: 7,
  },
  {
    id: "tmpl-orbit-os",
    slug: "orbit-os",
    name: "Orbit OS",
    description: "Interplanetary style showing dynamic orbiting constellation nodes, SVG paths, and cosmic theme lines.",
    previewUrl: "/templates/previews/orbit-os.png",
    tags: ["Space", "Constellations", "Interactive SVG", "Stellar"],
    category: "creative",
    isPremium: false,
    themeColors: ["#6366F1", "#EC4899", "#F59E0B", "#10B981"],
    features: ["Constellation Node Connectors", "Orbital SVG Ring Integrations", "Interactive Star Field"],
    sortOrder: 8,
  },
  {
    id: "tmpl-stellar-odyssey",
    slug: "stellar-odyssey",
    name: "Stellar Odyssey",
    description: "Deep navy and gold accents, featuring constellation stars, galaxy backgrounds, and premium typography.",
    previewUrl: "/templates/previews/stellar-odyssey.png",
    tags: ["Dark Mode", "Navy", "Gold Accents", "Astronomical"],
    category: "design",
    isPremium: true,
    themeColors: ["#D4AF37", "#6366F1", "#06B6D4", "#EC4899"],
    features: ["Elegant Astronomy Accents", "Fine Golden Divider Accents", "Smooth Section Fades"],
    sortOrder: 9,
  },
  {
    id: "tmpl-ai-digital-twin",
    slug: "ai-digital-twin",
    name: "AI Digital Twin",
    description: "Advanced futuristic identity layout with particle HUD layouts, neural grids, and AI-forward accents.",
    previewUrl: "/templates/previews/ai-digital-twin.png",
    tags: ["AI", "HUD Layout", "Neural Net", "Futuristic"],
    category: "tech",
    isPremium: true,
    themeColors: ["#10B981", "#3B82F6", "#8B5CF6", "#F59E0B"],
    features: ["Futuristic Particle Grid", "Neural Node Network Visuals", "Live System Monitor Dashboard Style"],
    sortOrder: 10,
  },
  {
    id: "tmpl-ink-corridor",
    slug: "ink-corridor",
    name: "The Corridor",
    description: "Hand-drawn gallery walkthrough — an ink-on-paper 3D corridor you walk down as you scroll. Projects hang in sketched picture frames, sections are 'rooms', with wobbly hand-drawn cards, masking tape, polaroids, and hand-written annotations.",
    previewUrl: "/templates/previews/ink-corridor.png",
    tags: ["3D", "Hand-Drawn", "Creative", "Interactive"],
    category: "creative",
    isPremium: true,
    themeColors: ["#1E1E1E", "#3A3A3A", "#5A5A5A", "#7A7A7A"],
    features: ["Ink-Line 3D Corridor", "Gallery Picture Frames", "Hand-Drawn Cards", "Polaroid About", "Guestbook Contact"],
    sortOrder: 11,
  },
];
